name: BlassityHub
main: com.blassity.hub.Main
version: 1.0.0
author: [Chaspyr, RobinMC]
description: Blassity Hub Plugin

commands:
    host:
        description: Credit for the best host ever
        usage: </command>